# Generated by Django 6.0.1 on 2026-01-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ability_type', models.CharField(choices=[('KILL', 'Kill Target'), ('PROTECT', 'Protect Target'), ('INVESTIGATE', 'Investigate Alignment')], max_length=20)),
                ('phase', models.CharField(default='NIGHT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alignment', models.CharField(choices=[('TOWN', 'Town'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.abilitytemplate')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='games.roletemplate')),
            ],
        ),
        migrations.CreateModel(
            name='GameRoleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('game_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_slots', to='games.gametemplate')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.roletemplate')),
            ],
        ),
    ]
