# Generated by Django 6.0.2 on 2026-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
