# Generated by Django 4.2.29 on 2026-04-09 03:33

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletemplate',
            name='alignment',
            field=models.ForeignKey(on_delete=models.SET(games.models.get_default_alignment), related_name='roles', to='games.alignment'),
        ),
        migrations.AlterField(
            model_name='winconditiontemplate',
            name='winner_alignment',
            field=models.ForeignKey(on_delete=models.SET(games.models.get_default_alignment), related_name='win_conditions', to='games.alignment'),
        ),
    ]
