# Generated by Django 6.0.2 on 2026-02-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_roletemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
