# Generated by Django 6.0.2 on 2026-02-28 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gametemplate_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phase_type', models.CharField(choices=[('NIGHT', 'Night'), ('DAY', 'Day'), ('VOTING', 'Voting')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('game_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='games.gametemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WinConditionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('ROLE_COUNT', 'Number of Role Remains'), ('SURVIVAL', 'Nights Survived')], max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('game_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_conditions', to='games.gametemplate')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.roletemplate')),
            ],
        ),
    ]
