# Generated by Django 6.0.2 on 2026-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gametemplate_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametemplate',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
