# Generated by Django 6.0.2 on 2026-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_phasetemplate_winconditiontemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winconditiontemplate',
            name='condition_type',
        ),
        migrations.RemoveField(
            model_name='winconditiontemplate',
            name='count',
        ),
        migrations.RemoveField(
            model_name='winconditiontemplate',
            name='target_role',
        ),
        migrations.AddField(
            model_name='winconditiontemplate',
            name='criteria',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='winconditiontemplate',
            name='winner_alignment',
            field=models.CharField(choices=[('TOWN', 'Town'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral')], default='TOWN', max_length=20),
        ),
    ]
