# Generated by Django 6.0.2 on 2026-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_winconditiontemplate_condition_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winconditiontemplate',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='winconditiontemplate',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
