# Generated by Django 6.0.2 on 2026-03-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gametemplate_is_public'),
        ('games', '0007_alter_winconditiontemplate_options_and_more'),
    ]

    operations = [
    ]
