# Generated by Django 6.0.2 on 2026-03-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_merge_20260318_1740'),
        ('games', '0008_merge_20260323_1434'),
    ]

    operations = [
    ]
