# Generated by Django 6.0.2 on 2026-03-24 00:24

from django.db import migrations

def create_base_abilities(apps, schema_editor):
    AbilityTemplate = apps.get_model('games', 'AbilityTemplate')
    
    abilities = [
        ("Kill", "KILL", "NIGHT", "Eliminate a player during the night."),
        ("Protect", "PROTECT", "NIGHT", "Protect a player from elimination."),
        ("Investigate", "INVESTIGATE", "NIGHT", "Discover a player's alignment."),
        ("Block", "BLOCK", "NIGHT", "Block a player from acting during the night."),
        ("Trap", "TRAP", "NIGHT", "Place a trap that identifies or stops visitors."),
        ("Vote Steal", "VOTE_STEAL", "VOTING", "Steal a target's vote during the voting phase."),
        ("Double Vote", "DOUBLE_VOTE", "VOTING", "Gain an extra vote for yourself or a target during voting."),
    ]
    
    for name, atype, phase, desc in abilities:
        obj, created = AbilityTemplate.objects.get_or_create(
            name=name,
            ability_type=atype,
            phase=phase,
            defaults={"description": desc}
        )
        if not created:
            obj.ability_type = atype
            obj.phase = phase
            obj.save()

def remove_base_abilities(apps, schema_editor):
    AbilityTemplate = apps.get_model('games', 'AbilityTemplate')
    AbilityTemplate.objects.filter(name__in=["Kill", "Protect", "Investigate", "Block", "Trap", "Vote Steal", "Double Vote"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_merge_20260323_1909'),
    ]

    operations = [
        migrations.RunPython(create_base_abilities, reverse_code=remove_base_abilities),
    ]
