# Generated by Django 6.0.2 on 2026-03-24 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_seed_base_abilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitytemplate',
            name='ability_type',
            field=models.CharField(choices=[('KILL', 'Kill Target'), ('PROTECT', 'Protect Target'), ('INVESTIGATE', 'Investigate Alignment'), ('BLOCK', 'Block Target'), ('TRAP', 'Trap Target'), ('VOTE_STEAL', 'Steal Vote'), ('DOUBLE_VOTE', 'Double Vote')], max_length=20),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(blank=True, db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('LOBBY', 'Lobby'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='LOBBY', max_length=20)),
                ('current_phase', models.CharField(choices=[('WAITING', 'Waiting'), ('DAY', 'Day'), ('VOTING', 'Voting'), ('NIGHT', 'Night'), ('GAME_OVER', 'Game Over')], default='WAITING', max_length=20)),
                ('turn_number', models.PositiveIntegerField(default=0)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_game_sessions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.gametemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('seat_order', models.PositiveIntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('role_name', models.CharField(blank=True, default='', max_length=100)),
                ('role_alignment', models.CharField(blank=True, default='', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('eliminated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.gamesession')),
            ],
            options={
                'ordering': ['seat_order', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, default='', max_length=20)),
                ('action_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='games.gameparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='games.gamesession')),
            ],
            options={
                'ordering': ['submitted_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_session_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'display_name'), name='unique_session_participant_display_name'),
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'seat_order'), name='unique_session_participant_seat_order'),
        ),
    ]
