# Generated by Django 6.0.2 on 2026-03-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_abilitytemplate_ability_type_gamesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaction',
            name='turn_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
