# Generated by Django 4.2.29 on 2026-03-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_seed_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitytemplate',
            name='ability_type',
            field=models.CharField(choices=[('KILL', 'Kill Target'), ('PROTECT', 'Protect Target'), ('INVESTIGATE', 'Investigate Alignment'), ('BLOCK', 'Block Target'), ('TRAP', 'Trap Target'), ('VOTE_STEAL', 'Steal Vote'), ('DOUBLE_VOTE', 'Double Vote'), ('ROLEBLOCK', 'Roleblock Target'), ('LOOKOUT', 'Watch Target'), ('JAIL', 'Jail Target'), ('DOUSE', 'Douse Target'), ('IGNITE', 'Ignite All'), ('IMMUNE_KILL', 'Kill with Immunity')], max_length=20),
        ),
    ]
