# Generated by Django 4.2.29 on 2026-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_abilitytemplate_ability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
